### ISSUE TITLE
DMS fails to push BFB file if PF net device is missing

### ISSUE THREAD

**Issue by killianmuldoon** [NVIDIA/doca-platform#2]
DMS fails to push the BFB file if the Bluefield physical function net device is missing from the host /sys/class/net directory.

To diagnose look for an error like the following in the DMS pod log. The DMS pod log will be on the node where DPU provisioning is stuck and will have `dms` in the pod name. 

The error in the DMS pod log looks like:
```shell
run command: grep PCI_SLOT_NAME.\*08:00 /sys/class/net/\*/device/uevent
```

To resolve this issue reboot the node that is being provisioned. This will cause the physical function drivers to be reloaded.

**Comment by adrianchiris** [comment]
Code modifications in DPF were introduced to eliminate this issue.
