### ISSUE TITLE
DPU stuck in "OS Installing" phase when connection is broken

### ISSUE THREAD

**Issue by wpeng102** [NVIDIA/doca-platform#39]
## DPU stuck in `OS Installing` phase when connection is broken

During DPU OS installation phase,  if the connection between provisioning controller and DMS pod is broken, will got the following log from provisioning controller, and then this DPU is stuck.

```
E1112 11:09:05.115109       1 installing.go:304] "DMS dpf-operator-system/worker1-0000-2b-00 failed to Execute activateOp, retry 1" err="rpc error: code = Unavailable desc = error reading from server: read tcp 10.233.65.13:34808->10.0.120.2:9339: read: connection reset by peer" controller="dpu" controllerGroup="provisioning.dpu.nvidia.com" controllerKind="DPU" DPU="dpf-operator-system/worker1-0000-2b-00" namespace="dpf-operator-system" name="worker1-0000-2b-00" reconcileID="3a26da9a-4b01-4bb0-baf0-5347faab4183"
```

## Mitigating the Issue:

Deleting  the DPU object will triger re-provisioning.

**Comment by Gal-Zaidman** [comment]
This was fixed by adding a timeout and retry mechanism, please close issue
